dbt_scooters:
  outputs:
    dev:
      dbname: dev_m0z9
      host: dpg-d44vvmre5dus73fdri70-a.singapore-postgres.render.com
      pass: 6h6Ni2hznTFQ5FEtVXYNRX17lB7fyhVJ
      port: 5432
      schema: dbt
      threads: 4
      type: postgres
      user: admin
  target: dev




floppa:
  outputs:
    sandbox:
      type: trino
      host: floppa.m2.ru
      http_scheme: https
      method: oauth_console
      port: 443
      database: iceberg
      schema: golden
      user: "flerinvs@m2.ru"
      password: "MegaFon19922605!!!"
      threads: 8
  target: sandbox